### ISSUE TITLE
Automation did not execute all the actions

### ISSUE THREAD

**Issue by costa-alex** [strautomator/web#10]
I have an automation with 2 actions:
- mute the activity
- write something to the private notes (uses a counter)

 The automation only muted the activity, the private notes did not update.

**Comment by costa-alex** [comment]
Here you have: 7431159827

Even if I do a manual sync, the private notes don't get updated.

**Comment by igoramadas** [comment]
Fixed in https://github.com/strautomator/core/commit/c1fe5137ce4460dfaa4c229d0501b7d071915b18.

To be deployed this weekend.

**Comment by igoramadas** [comment]
Fix is now live: https://github.com/strautomator/web/releases/tag/v22.275.12349
