### ISSUE TITLE
Automatically apply kudos 

### ISSUE THREAD

**Issue by paesku** [strautomator/web#15]
This is such a nice product! I stumbled upon strautomator while searching for the possibility to automatically add kudos to someone else's activity.

Unfortunately I couldn't find anything related to that in the official docs. Maybe you guys know more?

**Comment by igoramadas** [comment]
There's no API to automatically give kudos. Also I tried calling the front-end endpoint passing my tokens on the header but it didn't work. So this is not possible I'm afraid :-(

**Comment by paesku** [comment]
@igoramadas what a pitty. thanks for your answer.
