### ISSUE TITLE
Merge activites

### ISSUE THREAD

**Issue by cagnulein** [strautomator/web#16]
Hi @igoramadas !
I don't know if you remember me, QZ developer https://github.com/cagnulein/qdomyos-zwift !

I'm writing this because a QZ user ( @victorypoint ) here https://github.com/cagnulein/qdomyos-zwift/pull/1280#issuecomment-1437604488 pointed me to an issue of Zwift app that could be easily solved with your project.

In short, Zwift doesn't handle all the QZ stats to strava and the idea that we have is that we can merge the QZ fit file and the Zwift one in one only big fit file.

What do you think?

In particular we are interested about positive and negative elevation gain from QZ to zwift file.

Let me know!

**Comment by igoramadas** [comment]
Yes I do remember you :-)

So I quickly checked the issue, and I think this would go out of scope for Strautomator.

First, it would need to be connected to both Zwift and your app, so it could get notified of new workouts to then merge those files before pushing to Strava. Problem is that Zwift doesn't have a public API (only a private one), and Strautomator would need to open an incoming endpoint in which you would post your QZ file.

Technically, it's possibly doable, but I think that would be a very niche case for an already very niche segment of Strava power users.

If you want to try to spin up an instance of Strautomator yourself and get such integration done, feel free to fork the repo and ask for help whenever you need.

**Comment by cagnulein** [comment]
@igoramadas Thanks, actually I don't think we need access to Zwift API. We just need the trigger of a new activity, and when it comes from zwift and/or qz we have to merge the fit files.

Is this any better?

**Comment by igoramadas** [comment]
How would Strautomator get those files? Strava does not expose the original FIT files via API.

**Comment by cagnulein** [comment]
Hah! I missed this, I thought Strava does. Ok nevermind. Thanks for your time!

**Comment by igoramadas** [comment]
No worries :-)
