### ISSUE TITLE
Suggestion: Default linkback preference of "No links" for pro accounts

### ISSUE THREAD

**Issue by stevenwalker91** [strautomator/web#17]
Hi, 

Just wanted to raise a suggestion. I recently signed up for pro but my activities continued to have link backs. I quickly figured out from checking out settings that this was because there is a setting for it and the default value is 20% (I think?). Initially, I wasn't sure if my account had been successfully updated to pro or not and was a little confused by it.

I understand why the default would be the same as the free tier, of course it's beneficial for advertising the product, however, I think this could be improved by defaulting to the no links option (**for pro accounts**), but perhaps giving prescribers some form of motivation/encouragement to keep the link backs.

**Comment by stevenwalker91** [comment]
Apologies if this belongs in the core repo.

**Comment by igoramadas** [comment]
I'll add a notification that is created to the user when the switch to PRO is confirmed, with the details of what's included and how the user can disable the linkbacks, if they wish to.

**Comment by igoramadas** [comment]
https://github.com/strautomator/web/commit/2086e007b6f0371ef83870def79f1d48b1f13241
