### ISSUE TITLE
Edit Actions and Conditions

### ISSUE THREAD

**Issue by zecanard** [strautomator/web#19]
Please allow us to edit Actions and Conditions. The current way, which is to delete and recreate them, is particularly cumbersome for Actions that modify the Description, since copying the Action loses any carriage returns.

**Comment by igoramadas** [comment]
Updating the UI to allow editing existing conditions and actions will be rather cumbersome.

As this is mostly requested by power users / techies (5 people in total so far), I will add the possibility to edit the automation JSON directly, so power users can modify and customise their automations as needed.

**Comment by igoramadas** [comment]
Editing automations (directly via JSON) is now available for testing at https://beta.strautomator.com.

**Comment by zecanard** [comment]
The new JSON editor is very useful. Thank you for that!

However, it can also disable the “Save Automation” button. To reproduce:

1. Open an automation for edit.
2. Open the JSON Editor.
3. Close the JSON Editor.
4. Add New Condition.
5. Save Condition.
6. “Save Automation” becomes disabled.
7. Open the JSON Editor.
8. “Save Automation” becomes re-enabled.

**Comment by igoramadas** [comment]
Fixed and deployed: Live now: https://github.com/strautomator/web/releases/tag/v23.204.12240

Still having issues with the dark theme of the JSON editor, but hoping to have it sorted out within the next week.
