### ISSUE TITLE
Show “Stop executing further automations” in Automations List

### ISSUE THREAD

**Issue by zecanard** [strautomator/web#20]
Please consider adding a visual indicator to the Automations Overview to indicate `Stop executing further automations`. Right now, we have to go into each individual automation to see if this setting is enabled. For Pro subscribers with lots of rules it can be hard to visualize the flow of our automations.

This could be made to look similar to the current `DISABLED` indicator, except to say `STOP`.

**Comment by igoramadas** [comment]
Available on the https://beta.strautomator.com environment for testing.

https://github.com/strautomator/web/commit/204d69a2de71aefa37f53ab536631b66abf649af

**Comment by zecanard** [comment]
Looks good! Thank you for the lightning-quick turnaround!
