### ISSUE TITLE
Weather tags don't seem avaialbe when wanting to set a description of an activity

### ISSUE THREAD

**Issue by gkohen** [strautomator/web#22]
First of all thank you for building this automation tool. Super!
As I signed up for Pro and was trying to set up some of the automation I was wondering how inject thge weather and noticed it seems to be missing from the tags.

Maybe something I'm missing. Cheers. 
<img width="810" alt="image" src="https://github.com/strautomator/web/assets/2158006/e534a3a8-0a80-40e0-ad2a-4ecd98cafecb">

**Comment by igoramadas** [comment]
Hi @gkohen, sorry for the late reply, I just came back from holidays. The weather tags are available, if you type "temp" for example you'll see the list of temperature related variables. Same to "wind", "humidity", etc.

The tags shown there on your screenshot are just the initial ones (most used).

**Comment by igoramadas** [comment]
I will update the screenshots with the new view, and will also add a link on the dialog to display a list of all the available tags. This should be ready by the end of the month.

For now, you can get the list of tags [here](https://github.com/strautomator/web/blob/master/components/recipes/AddAction.vue#L151), around lines 151 to 256.
