### ISSUE TITLE
Activity debug menu

### ISSUE THREAD

**Issue by Glennmen** [strautomator/web#23]
It would be very useful to have some kind of debug menu in activities that show all the available information for each tag.
Currently I have Strava + Garmin linked but I have no idea what tags are available and the information that they contain.

This would make it much easier to come up with nice automations and maybe use some new tags that I currently don't know about.

**Comment by igoramadas** [comment]
This is on my to-do-next list. I will create a view where you can input an activity ID / URL and it will show all the available tags and their respective values, including Garmin data and sensors. But I'm "busy" with work + vacation this week, so most likely the new view will be ready for testing only by the end of the month.

In the meantime, you can get the list of all available tags for [strava](https://github.com/strautomator/core/blob/master/src/strava/types.ts#L11) and [garmin](https://github.com/strautomator/core/blob/master/src/garmin/types.ts#L28). Any field of StravaActivity or GarminActivity (if it was recorded with a Garmin) can be used.

**Comment by igoramadas** [comment]
Activity debug view is available now at https://strautomator.com/activities/debug
