### ISSUE TITLE
New tag: AI provider

### ISSUE THREAD

**Issue by Glennmen** [strautomator/web#24]
It would be useful to have the used AI provider available as a tag.

For example my use case: 
I have set Gemini as preferred AI provider but remember reading in the release notes that this provider has been disabled due to EU restrictions.
So it would be interesting to my to have the used AI provider be available in a tag that I can use in private notes for debugging cases. In that case I can evaluate which AI generates my Strava activity title and maybe even update my AI preference.

Also in case of fallbacks it might be interesting to see which AI generated the title.

**Comment by igoramadas** [comment]
Hi @Glennmen , I'm currently bikepacking and won't have time to do it this week, but I'll try as soon as I get back by the end of next week ok? Should be fairly simple to do.

**Comment by Glennmen** [comment]
I wanted to close this because I had seen it working this week.
But then I remembered in [release `v24.164.11218` Gemini was disabled ](https://github.com/strautomator/web/releases/tag/v24.164.11218) but then when I tested the new tag in my private notes it mentioned Gemini.
![CleanShot 2024-05-31 at 16 12 06@2x](https://github.com/strautomator/web/assets/11406433/958ddf2b-e323-4137-98b2-c78f33c58b74)

Is this correct? If so the issue can be closed.

**Comment by igoramadas** [comment]
The latest model of Gemini 1.5 was disabled back then. But the provider is still available (using the older models).
