### ISSUE TITLE
Feature request: Allow Last.fm tracks to be added like spotify tracks

### ISSUE THREAD

**Issue by Nick2bad4u** [strautomator/web#27]
Would this be possible?

Last.fm has an API (https://www.last.fm/api) and it's free to use if you make an account.

It would be nice for tracks I listen to locally and then scrobble to last.fm to be shown during workouts instead of only Spotify.

I've worked a little bit with the last.fm API if you need any help.

**Comment by igoramadas** [comment]
Possible it is... but that's a very niche use case, and you are the first person asking for it :-)

I'll add to my backlog and do some investigation around how many people would possibly use the integration. If at least a few dozen users, I'll implement it.

**Comment by Nick2bad4u** [comment]
> Possible it is... but that's a very niche use case, and you are the first person asking for it :-)
> 
> I'll add to my backlog and do some investigation around how many people would possibly use the integration. If at least a few dozen users, I'll implement it.

Dang! well let me know!
