### ISSUE TITLE
Feature request: Perceived exertion

### ISSUE THREAD

**Issue by Nick2bad4u** [strautomator/web#30]
Is there any way to automatically set the "perceived exertion" on activities?

I noticed ActivityFix cannot do it either. Is this an API limit issue?

**Comment by igoramadas** [comment]
This is a limitation that actually makes sense, in a way. The "perceived exertion", as the same itself suggests, should be used on a per-activity basis to describe how hard (or easy) you felt the workout was. Regardless of power, heart rate, speed etc. It can't be derived from other metrics.

I doubt Strava will ever allow setting the value via API.

**Comment by Nick2bad4u** [comment]
> This is a limitation that actually makes sense, in a way. The "perceived exertion", as the same itself suggests, should be used on a per-activity basis to describe how hard (or easy) you felt the workout was. Regardless of power, heart rate, speed etc. It can't be derived from other metrics.
> 
> I doubt Strava will ever allow setting the value via API.

Ahh okay. I was curious bc I was going to set all my short walks to easy but I figured it was an API limit. THanks!
