### ISSUE TITLE
Line breaks in user provided text are not visualized

### ISSUE THREAD

**Issue by PabiGamito** [strautomator/web#31]
It would be nice to be able to see where I added line breaks explicitly in the description of automations. For example for the content to append to a description of an activity, where the line breaks do matter to me.

**Comment by igoramadas** [comment]
I would need to redesign the automations view to get this done. The current UI is optimised to be as compact as possible. Will try out some changes next month. If you have any ideas feel free to open a PR / post a mockup here.
