### ISSUE TITLE
Moving/Elapsed time

### ISSUE THREAD

**Issue by costa-alex** [strautomator/web#8]
When creating new automations we can set conditions based on the moving/elapsed time but the time picker requires an AM/PM setting which does not make sense.
If I set a condition with "moving time less then 01:00 PM" after saving it changes to "moving time less than 13:00".

How can I set an automation with a condition like "moving time less than 1h"?

Thanks

**Comment by igoramadas** [comment]
Hi,

I'm using the native "time" type of HTML input fields. I wasn't aware it would follow the AM/PM standard based on the user locale, even thou its underlying value is always using the 24h format.

For now you can set the condition as 1:00 AM which will translate to 01:00h. I'll get the native "time" type replaced with a custom pattern by the end of the week to fix that annoyance.

Thanks for pointing this out.

**Comment by igoramadas** [comment]
https://github.com/strautomator/web/commit/0c499aa88be03391f248538da36742f716db12a1

**Comment by igoramadas** [comment]
Fix is now live: https://github.com/strautomator/web/releases/tag/v22.275.12349
